spring.application.name=nexoai

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/nexoai_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8085

# Thymeleaf
spring.thymeleaf.cache=false